apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-prometheus-stack

resources:
- base/clusterrolebinding.yml

helmCharts:
- name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 77.5.0
  valuesFile: values.yml
