---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-runner-token
  namespace: gitlab-runners
spec:
  encryptedData:
    runner-registration-token: AgBiJv87+F8yucWaCbLp0e4x2rXGABk/zEUMlLz507UCmjYlJ/xze65EC4KETcQMU41d916Lye2jOTEsZTq4EoLqca+FVzSH8ip3QnuJnZ3jy21i0sXH+eDYnF7GtWWTnLe5F35ATfanQrFxYECpHE0oa7MdJ7doBkAuC9BN4CeFhedhT2dS0TUZoExLvIvYn9LCCfdLu0x8LLKjF8c3HeYbXM1uMuga/mn1YaCliHou9XFShpChTjm+OtDdwJoGEC0ZP3YbztTNTn30noePuJnumeagcHdbhWqQTBUeLUFLZrVE5D7PPqguL+VI4okBYzmUoayZ13yQn4TgcNdthH4fa95SfDSmwJqpIJcH/T7tIPgZ27EdcO9MQBf/m92AJzTE4osQAhbGHNHeqB27qYiy1hnvv0yMVuZwQWFZ14m5aIJpOvyXRxIyFKNoMIIkKGZjFHE952YagtFgb5PZjOQqZevLtBtMUvznhFEHMHCU6YkAPMebduv5VxNeV80pIjl6d5tE9ICERjQ4zq8/KxCGx3BEN878u2dWDJVifrkJW/4x0C2SWApo4ZGLf4gZlMDvRgKNCGEY4io0UHlPvIJAAo5xyodycXomrUIsPNnT7lgIUESL5Dn4K6cOiHshCIB0ciqaMdknKdU4/va6oqtP2gtaQkFP7x3ToKSKW0nTRcMaJ+OLT+9OvwkPtujtvH91Kr6eZXam7El5HyHBtpVeAugfbuYTbh5+XzvgkOPjnyr9R24I4MJHwUphUQevZaWRtIUMj+FlWnOJc8jC0lMk
    runner-token: AgA+A1a2E0WD7unb15Hinxdlha4gxUV/LcsqtRai43qmOmsv8WsMdB47BVBGQpMOZzkfQ6XMAibgwanYdTZ7CMLqm34Vo7yL5b2RYiz0EgIMYmEulbAufTLoLuk7ea5TEK4hE9lQWyKpZMyZcOC7+42JYoR/lMvYpxqK6fP3ssl2ZulDbFTm6MlcgTkoSdmWVES7DcQ3QlH5oCNjA8T85O6giTB1thZT/PSjuefNV8FrIVAzJuq3O1pQXGqLPV+14Hw4UYbt7d3jdgBTzNWc37/HW1yBxRPWr5VXbkSvOuR6jw9j4doALvsQovHROxrQ6/ZYTW6EAl3KPkEA6pdE4Bt51yxOn2JhDstkMo6v2eJSeAwmm0Fe5xWtBpgIEOUZ2sMdlV0q1W1MCT72PVvgUojesM/tKho1TDioSjRL+hISa9yhEL1CEWNqjDgaeOl1aIjj0rpRagFoHUjblm0EfVAdopJFwGoCVGXV6HsgeijFChXrvYRM+FOwkUT+xBpdHeZ0Gc53BU0k/IrH+3LRED+WNy1F17P5fq7s7+0K6PYT+HGJ7jLHqcqogctkABGNsWRb8n5YgWKa5wDpnd5oAnHZM1bw/sVmIAd2Mcy7K0UiujTYrLcGTTBNDOwLfN4kUSqFra8v3bfyr7BVay35nb4k0b0H8PJSyWq61EMrJcWE3HgncKcNZUTE3CkMNt5D9rTjkaYumQmHt8fRZsxlE5QiI3DQVgWqKuYV4AVU9/UVh/3GY2sS0mvbv8gQ/ebbbWsg24UfYgk3WQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-runner-token
      namespace: gitlab-runners
