apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: forecastle
  namespace: forecastle
  releaseName: forecastle
  repo: https://stakater.github.io/stakater-charts
  valuesFile: values.yml
  version: v1.0.158
  # includeCRDs: true
