apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- base/bgpadvertisement.yml
- base/bgppeer.yml
- base/ipaddresspool.yml
- base/scc.yml

helmCharts:
- name: metallb
  namespace: metallb-system
  releaseName: metallb
  repo: https://metallb.github.io/metallb
  valuesFile: values.yml
  version: 0.15.2
  includeCRDs: true

# resources:
# - https://raw.githubusercontent.com/metallb/metallb-operator/refs/heads/main/bin/metallb-operator.yaml
# - base/ipaddresspool.yml
# - base/metallb.yml
