# deploymentMode: Distributed

# distributor:
#   autoscaling:
#     enabled: true

gateway:
  replicas: 2
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: iaas-wcooke-me
      forecastle.stakater.com/appName: Loki
      forecastle.stakater.com/expose: "true"
      forecastle.stakater.com/group: Observability
      # forecastle.stakater.com/icon: https://loki.apps.iaas.wcooke.me/
      forecastle.stakater.com/network-restricted: "true"
    enabled: true
    ingressClassName: openshift-default
    hosts:
    - host: loki.apps.iaas.wcooke.me
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - loki.apps.iaas.wcooke.me
      secretName: loki-gateway-certs

global:
  dnsNamespace: openshift-dns
  dnsService: dns-default
  extraEnvFrom:
  - configMapRef:
      name: loki-bucket
  - secretRef:
      name: loki-bucket
  extraArgs:
  - -config.expand-env=true

# ingester:
#   autoscaling:
#     enabled: true

loki:
  auth_enabled: false
  limits_config:
    allow_structured_metadata: true
    max_label_names_per_series: 1000
    retention_period: 1440h
  pattern_ingester:
    enabled: true
  schemaConfig:
    configs:
    - from: 2025-01-01
      index:
        period: 24h
      object_store: s3
      schema: v13
      store: tsdb
  storage:
    bucketNames:
      admin: loki
      chunks: loki
      ruler: loki
    type: s3
    s3:
      access_key_id: "${AWS_ACCESS_KEY_ID}"
      bucketnames: "${BUCKET_NAME}"
      endpoint: "${BUCKET_HOST}:${BUCKET_PORT}"
      http_config:
        insecure_skip_verify: true
      s3ForcePathStyle: true
      secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    object_store:
      storage_prefix: os
      type: s3
      s3:
        access_key_id: "${AWS_ACCESS_KEY_ID}"
        bucketnames: "${BUCKET_NAME}"
        endpoint: "${BUCKET_HOST}:${BUCKET_PORT}"
        http_config:
          insecure_skip_verify: true
        s3ForcePathStyle: true
        secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  ui:
    enabled: true

# querier:
#   autoscaling:
#     enabled: true

# queryFrontend:
#   autoscaling:
#     enabled: true

rbac:
  sccEnabled: true
