apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/dashboards.yml
- base/namespace.yml

helmCharts:
- name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yml
  version: v1.18.2
