---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-oidc
  namespace: gitlab-system
spec:
  encryptedData:
    provider: AgBGfFC6zxqLSc4Xzv+6PNXFooXOyQI1O4KX7vs7Eol9h6xzZWnqav6wA3wj7dvU4mNzRJuVQTBiNvu36upEfBj/QZbx2oxv5mp0GFKUX5xTQfB58yfciAsF9St1MhfoX4PyefVLrTpjWhAuLqwq8M1ZSDn8PZqTC2ZUHtNUQsE/prIoj5sqEn/G0bo0YcN4GrR3zNvbABl8/aHeAx44O9cSs07EUyx1uyLIJ3sAl4PdcNk4qHcBRMRNVvuV2SqDk1HmODvappHvg+quglni0DfZYlUuYWVAFTFfR4eHMr8LvSNNLFe6A7L/gYZJIaLY31At2h0QqrZiQ8si0P9Br4vG3AhYmn4GqELnE5VhBoRzeU8wo9VljyTZZyHj2GxLzI6rJMqyrTNua8LUDAukN/zI7Pocpi+XXiha70Eks2IbMuyD98lVS9zdWbmsTWMJjgDTwB/puP7xnNvFge7bsjuAWW5ILwjOzDxOLj/f/j5/1Rwi3059XlJwHrIeEKiq7Az4Aj5SDekWfIQo0wJcI9wVxY8IfB360lYO5VyO8/nt4LRPPvY1WHzqj8oXdafLZW1QBad8yT0CPPDJz9T+NGaLCOBiO0PlsbmSY4G32Ww1rj+H6GD9HfJPcUuBZXn04pD5rzqtnXriO1AJY9im0XxyhRYw2e6W2q9uOEEiyW7U/I2Mw3BJR8T1ChK+n9vWfLGlMDQIHP5ncNlMEdGlDPm46kKHwKHfPh+DjE72com08Rqzf+jlRYjBIHeAxKWE//sLC/cZQR79Tbx7uk0nZE/r2VeO6MSDEXCuzehbEw/ZO0EtJ4/rmvmJEaF05jjVvav5W2a5lqdObq/OIFi7ZemPxIyVZV3khPsdhBSVSXjiaHHKTYGK5kruKo2TJr9Vek/zXYbzUsRhHnX7Hzja6UK1SKJGQKUodNU3hWR7/UdwhbRi1IiTryv+JRfTMMmjDmj0BM6uZhZ/exf/JWBe35GWz4+ySNRdtygLXja76sBFR6ltQE4tcvqAYXcDA8b0M7xt+lqyyJWmU0d0yVFNQ7p+CCXlqq7cZtkmGJZfomb/qSDxG7WsQYVOySYYsgrSIYsP4kXoNEFJ4C1sZtxY8wSbWxv5FxY5Rkaum8rAJdJxOmCnzBqTdLlYpKGbJOXvxZh8UHmOt+Nq0wAcfYEY7cJHWfU1ADSRkzaN3zbC+CtGCLUYW3rpJ2uunoT/zxvIrvT2srdETcLbem88GcZSG+P1ecdTo1PUFzTHk2wLMfplYMHne08zwJwoZ8Vugw3JOsROgrpLKH5qpVQ0g7cbM3qfqs0l/ynvncDi3wDaXVTQayjxa0uBm8elVTkz1ERcJ3XAdh6uK1vNNui7HI8FIT7sEikWZp4kWssVmJ2T6ZnrqS8pkhxvnbG7FYXlz7arFd3opMVykIcjok4NbVfTgfpB+YGZGcBlVD2z+D03EzJJT5MGEv2UhRgMX+UXTiAqQCHUVgcppnYQM3SAqqaGp9PnPse+fGuOrX4/KM6JpA==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-oidc
      namespace: gitlab-system
    type: stringData
