apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-datasource
  labels:
    grafana_datasource: "1"
data:
  ceph-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Dashboard1
      access: proxy
      jsonData:
        httpMethod: POST
        timeInterval: 30s
      type: prometheus
      uid: ceph
      url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090/
