apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-datasource
  labels:
    grafana_datasource: "1"
data:
  mimir-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Mimir
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
      type: prometheus
      uid: mimir
      url: http://mimir-distributed-nginx.mimir-distributed.svc/prometheus
