---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-keycloak-client
  namespace: grafana
spec:
  encryptedData:
    client-id: AgCeHLnLi56uLndmbbbAprOWflfKvrUpj98e94F/aau0hKhqc3XF90HUk5K73n5l9ymCUR7EKFC3wpXvR3qrD86yNybOJ94d7fW9Bd/pIVnewM+NcU4qGzz5YkRJ6GLLcoLsCu92cDXTYGctuRF5DJb+HWv21KdbGrT0n66V1IH36thQW4CGKRbT4ZqFfL3AcWUYtStCY3Trya7K5UY+1Covui2mwxOb9tkr8YdulFfvGqEWplasW1FGNtQCClp+4lG4hp/nQkqpGkPRGj7qJoMqeV48u/5qWKnpgTf3IdHvqPmxZ+qJKu29mT2m6CV8U4WlTozdMPh6aySU7/GkUxbgElzUrNuvylNDUMX5IJ+XVEhGBWJrJHPwKxI+DgE44+7uJp+1YtB6dkpE5nZhJyK4xPs2v32Cio5UDeyfoTFestIzBZdY/YYAIY1Rx0M0+Ca1Z8+PjyVAzJj1Yi6NyQAGQR9zOURMsDR1DCEAP91x7766SmXYEJoe6Jder1sKU0m3Ud67JAFr8lkIYKqcmPWskUsDxWyvpfglmihKURD9ZPdHK7cDjoiOrHQ2n4dwAjCegwk52IrM3WI1pFWZb8QqrR7JRjEIRK/ogyyRNqSyymUmkczjIo6f2n1nQbEF7ZvEHpIAluxaRLKTEXeDGQmiPMnxX840TNOZgA1V8nkGfyLnL2rUgE4fdrC1U71mLaFDD6xPQSqD
    client-secret: AgDPdzx6NGFsV9mav3njtxye678u1pzaas647lljqIyDHiES4/UfyzZBOPRD8IWeRFFKoV/cF4xlkqk9xHaJ3DjwETJm/TSHodcismVxvjGZs8PH0IKOzCaNdodw9UAnNR7bgfyMe2P+1dB7fnxUe+9BMBpCZb3x9T50SfqwOskjk/lyAED0mTb6roamPs90/gfPKF0T/3jyo2VeQ6vY56RqTFZviMtQOKzrGebo+sP46vhIk+JHd10ydOkozt9qr7lWe571Q5o6pwulKs4B/gQsURay0F+0kGIIFmGTDg7N2Gl5/7ZfN2BuEbGjPlu1GcdVldnP1/HyBGW7l/fQ8pT0xTH2wwXhg9K8h1Ee/+0PYX5ioeh4OJpSXL3rTbD77NxczIKmT4Ln+m433VYMKR09li63Ts6tkE0xz3GStF5Z2h3BC7wIFUsw92DQFsFlzR/y83FC552brOQJIOxboW6p8ZRUv2cOGgwzN3/w7gq3YYJf5Va+zFNg0sfVYQdmgnS56lJuY2GnEIIPFfJVFjB5KhJJHokT1G2KcVXwttHSzV/u+dMLWN1h2FwREpVjNUC2scS5nh7YmSMCDoBmUzFrxRoENMiu7yJmpNUmJ0PeBSkatJTD6gaUa3xxOPmYSVHYvXqq7N3OJZzJ8de6zOVoy726f8nLUERGoYbV3ziqnzauXd0f6skf3OBJJFUoTuAkqcTLJQK/C9y1qfvPUhKTfq5Uz5PX0cLKJnOrrT1q5A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-keycloak-client
      namespace: grafana
    type: stringData
