apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph-cluster

patches:
- path: patches/scc.yml
  target:
    kind: SecurityContextConstraints
    name: rook-cluster-rook-ceph-cluster

resources:
# - base/dashboards.yml
- base/ingress.yml

helmCharts:
- name: rook-ceph-cluster
  namespace: rook-ceph-cluster
  releaseName: rook-ceph-cluster
  repo: https://charts.rook.io/release
  version: v1.17.8
  valuesFile: values.yml
