kind: ConfigMap
apiVersion: v1
metadata:
  name: ca-certificate
  namespace: openshift-config
data:
  ca-bundle.crt: |
    Bag Attributes
        localKeyID: 2D 79 32 28 C4 65 B5 52 AF 50 4D D0 32 F0 B2 31 0E 40 83 C6
        friendlyName: iaas.wcooke.me
    subject=C = US, ST = CO, L = Colorado Springs, O = WCOOKE, OU = SUB-CA-CERTS, CN = iaas.wcooke.me, emailAddress = wcooke-certs@wcooke.me
    issuer=C = US, ST = CO, O = WCooke, OU = WCooke, CN = WCooke ROOT-CA-1, emailAddress = wcooke-root-ca-1@w.lan
    -----BEGIN CERTIFICATE-----
    MIIGVzCCBD+gAwIBAgIUaA9IplaI1tVrrUeh8zcBB6TAOiwwDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNPMQ8wDQYDVQQKDAZXQ29va2Ux
    DzANBgNVBAsMBldDb29rZTEZMBcGA1UEAwwQV0Nvb2tlIFJPT1QtQ0EtMTElMCMG
    CSqGSIb3DQEJARYWd2Nvb2tlLXJvb3QtY2EtMUB3LmxhbjAgFw0yNTA2MTUxNDI1
    MzZaGA8yMDc1MDYwMzE0MjUzNlowgZ0xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJD
    TzEZMBcGA1UEBwwQQ29sb3JhZG8gU3ByaW5nczEPMA0GA1UECgwGV0NPT0tFMRUw
    EwYDVQQLDAxTVUItQ0EtQ0VSVFMxFzAVBgNVBAMMDmlhYXMud2Nvb2tlLm1lMSUw
    IwYJKoZIhvcNAQkBFhZ3Y29va2UtY2VydHNAd2Nvb2tlLm1lMIICIjANBgkqhkiG
    9w0BAQEFAAOCAg8AMIICCgKCAgEA1Qc9lSZycyvqvjd/aOqkJj2c0odzjpqTWOGL
    zTSqOs0EuK2KqyNeoWf0dmCEAYIWArS+PvqvwQ2z7b8GGJOPhNEElw8gQE87y8xt
    93a1fzQqczWL3h43jIhWzBMEKAqxa9bn7FOMLTFYiPMjb4SnHxxlqyE+y6/XQUrT
    iQw+RH4zmIWttQM1gOiKMMzEf/V/80GRnT4557xRNS/4sBP0kbNYUzV2q6ZV1W1l
    RQXCwC+uY+DGI9NA6LrrIGISM/cyyAWGIirkLpjn2uc13EfsMk05Hr0uFDumaPdv
    UBxkzOWa0T2wLMKAI3RlYHFmJNl3EKwK9+p/J8bQqLqfoKhUm66RP6pBKnmLGVUK
    9SJP4udXRNZq25+8qujJfGVHjajc8hKJ7jEDF3ZCwijXqENoXHf2A94skA/vYJCT
    TO7TrWuYEhaeJcxnsfTwZce2IpvU3ZkDG9z7k0XontqKeAyQ6P9tEeC2mnZaGMpE
    PHWXiiK3eWDdByHl6XnVqGj2aMZ+fP1NuDSf1BwGQEt0lhjZinc2MX98YcJGX2/U
    AbV8ginZP4KYc8nogI2cX9jC8aT77h/wZ6XNRcJhusEGIaKANj/EmvYeWk2z4AO4
    lbtzvNtQpyGEhz5Y/ps759p9BEWd9Ljvzbc6QgCmaiMEqn3ZDqLndsxJBEJc+8Qa
    J3zVWb0CAwEAAaOBqjCBpzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
    xjAhBgNVHRIEGjAYgRZ3Y29va2Utcm9vdC1jYS0xQHcubGFuMCEGA1UdEQQaMBiB
    Fndjb29rZS1jZXJ0c0B3Y29va2UubWUwHQYDVR0OBBYEFNGVe5jba/jUOGBCjgzj
    RsC46CddMB8GA1UdIwQYMBaAFJUgOkh2PalMTJ1CoX+vs7tFvil0MA0GCSqGSIb3
    DQEBCwUAA4ICAQAkDevvCxqsBWmYXu9eb1FzvpkO18TmMZZHRyMbMCtuVBISCt1p
    yzV5QZUtQShmId6fuHSxBV97xjSuLA1QbskvI4cdWeGmGbf7u+guMeh/rwTfWvuy
    XL4eVSIQW5zoMbzbMebY2IGRHGO6IJuHv+Vqo5Bnj1TXiCUBI1QtR8Nfx9Mj2Tva
    oYs4d4ebvnyYtX2+Z/pKM1nGFb9DAqrh2hmFvPdd1y08Dqy7efp9dx6IoAeEijfY
    oEvfmyVV52BlNl0MmhbexPdjgJMMbVAhtjqErPgLPfdGpb5JUWFFxZLdY0+T/2sj
    3C5EzkpPFSu+xy38oO8oY8/DMxno7zDbJgDA/WS7hBI6c1/Udlw7sGzB/rteTPNv
    egM1hGnj75ZLTeulWjGf4X+1FoKarEWpzpAE/Ww+VRZf3lcm6OBxE3oim9lkH5Ti
    Z1jCjdvr57t1JGnjkp5tsXfSAW5H3n63ezoJKw1WZsPBmHlAuHc84nxqdYUo9s6n
    flo7RvNkzca+wRwSyZ2zlM/yGx5OE88E2/x10NXDH3zCJu4dNVldR0cVp7z6jW2k
    eebD4jUYHQRmUHF3AW/fIVZzmyX5XpKaD6cP61a7yw7tn+jfbOV336pIXtfiOz1d
    MADr/U69kyPotK3gjC88YETjUcaNSo6mZE/WQGa8xk7cLuS6Nw0rueiy4w==
    -----END CERTIFICATE-----
    Bag Attributes: <No Attributes>
    subject=C = US, ST = CO, O = WCooke, OU = WCooke, CN = WCooke ROOT-CA-1, emailAddress = wcooke-root-ca-1@w.lan
    issuer=C = US, ST = CO, O = WCooke, OU = WCooke, CN = WCooke ROOT-CA-1, emailAddress = wcooke-root-ca-1@w.lan
    -----BEGIN CERTIFICATE-----
    MIIGFDCCA/ygAwIBAgIUUWCMxxzlCxts9XL7GMEPXarS6dcwDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNPMQ8wDQYDVQQKDAZXQ29va2Ux
    DzANBgNVBAsMBldDb29rZTEZMBcGA1UEAwwQV0Nvb2tlIFJPT1QtQ0EtMTElMCMG
    CSqGSIb3DQEJARYWd2Nvb2tlLXJvb3QtY2EtMUB3LmxhbjAgFw0yNDA0MTMyMDQx
    MjdaGA8yMDc0MDQwMTIwNDEyN1owfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNP
    MQ8wDQYDVQQKDAZXQ29va2UxDzANBgNVBAsMBldDb29rZTEZMBcGA1UEAwwQV0Nv
    b2tlIFJPT1QtQ0EtMTElMCMGCSqGSIb3DQEJARYWd2Nvb2tlLXJvb3QtY2EtMUB3
    LmxhbjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKcZtT1P/iHd5mLA
    Tj+p1Sv3qCzG7w8B9MNsvZAKRR/how+4WspBlE5scVrbBwgn82fdF1U35qzsts/g
    vNfcL9ziSb91z1XLfzPOqdOoI7Q9DD4pyPv5bJFjhz0fm4iPlqu1aBfYRHOcEdWB
    thl7hobh3BCa6rO8MzCuQZ0NEva7uNYztHw3T+X3/yuSOnW6gViibANZliK1bRFk
    lk/w52ol/Vs7eNsUzv6wXcWB05hCt4IkvENTh0H/Pa/imegEK7wufKRHTQwwBzlR
    GlNuttRHeJbCdE+L0Gzp2MMDE/YxbgUPbAbUg9o1Dnm4yu98haDOXKU9d2RelvU6
    1Gg7QACiSfqoOY40Ad2ifYNH2iumDj4PTRYE99wW3klqdXpHL6JkR9nIu0dCjAlh
    pKRyjhmQ/rOF6n0tL2iCorIQNK7rqakNmmdrjRkpCLOcBkx171iIC0+UjxyL3jCD
    j3Rq6yPxEzGN5IrbdgyZUQ9NoPsEkEhVlZn8KBvdD121/RZSFO+0ZFDC2mNfYFbG
    /GZtPe1ZuCZS4Ka4A8b66SA0AGjAR/QNq+hjzH0x9bW8IO4whmaij7bJGgjnqHC4
    oFNT2snnecTK3UTWjwLS/W+/KhhEYlP5zS6RbXBzB8xY7BaiR3wmUFO8QUWM/Qh4
    61tokMOfuhyO1Ay/wKoGT0CgJ4nNAgMBAAGjgYcwgYQwDwYDVR0TAQH/BAUwAwEB
    /zAOBgNVHQ8BAf8EBAMCAcYwIQYDVR0RBBowGIEWd2Nvb2tlLXJvb3QtY2EtMUB3
    LmxhbjAdBgNVHQ4EFgQUlSA6SHY9qUxMnUKhf6+zu0W+KXQwHwYDVR0jBBgwFoAU
    lSA6SHY9qUxMnUKhf6+zu0W+KXQwDQYJKoZIhvcNAQELBQADggIBADNdWfV9KS5l
    NEadQjhMH0vXg5lPVtwhVdPLAC03FuDZ2qyn4i++0Q6XsfTNC0o2u/wwijJj5s2p
    qxlK22fx0Z6FwcWD4i36XwYGTkz+nZkIz5Cu6cJo905i/CjeRi1zvHYoGQTclSQy
    ZvhZo+lv77ruEmb5PhzLblvnzkRZ2CXTIt3xXYCo3L5Tspd81eT4rvdpcJ387Vwc
    I3jfuJRMCGB6fwBLOXRssjbItYOj0EvR+a81D5V5IfcONb3Ws+bPh4+SooQPqSCH
    o19GXRezsV3pvKsWNiVphwMj/U6RYxEL0lQUINE0RgDZeL6U3d4AiyfLOsccHDW1
    ceJZo8R3Rvg2AIpE3agpimTCTFZ6FTFHMJyTUVXP+a/UG5+VQ6yQpSFlFhufp3US
    6P4Fc0X8X4h6PwOq0ePc9TSGBGqBv0n6BPWzWI88Gchm9TnMdylbFJKXBuxLIVw+
    hgApN6JUGdVpyCyH0mNCAAVDweett2k0Jtl3s39qRFJiExPfeHBizYBVH3ojL1Zo
    c0alEC/DrTg7NJ35ZmMtdVkJM2QRMPar68eFveBuAjIlNVfL/X3rWn9ysMKTMq5r
    Pz1DZp0qxAc7eGd+SgTQJt2LTVjB6wGG7pWebI5vNlkbiOfROpqCfcUQR727FZjE
    EYORZixooIg8wvIOHlE6xVB7t2TUOraL
    -----END CERTIFICATE-----
