apiVersion: v1
kind: ConfigMap
metadata:
  name: root-ca-cert
data:
  root-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGFDCCA/ygAwIBAgIUUWCMxxzlCxts9XL7GMEPXarS6dcwDQYJKoZIhvcNAQEL
    BQAwfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNPMQ8wDQYDVQQKDAZXQ29va2Ux
    DzANBgNVBAsMBldDb29rZTEZMBcGA1UEAwwQV0Nvb2tlIFJPT1QtQ0EtMTElMCMG
    CSqGSIb3DQEJARYWd2Nvb2tlLXJvb3QtY2EtMUB3LmxhbjAgFw0yNDA0MTMyMDQx
    MjdaGA8yMDc0MDQwMTIwNDEyN1owfjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNP
    MQ8wDQYDVQQKDAZXQ29va2UxDzANBgNVBAsMBldDb29rZTEZMBcGA1UEAwwQV0Nv
    b2tlIFJPT1QtQ0EtMTElMCMGCSqGSIb3DQEJARYWd2Nvb2tlLXJvb3QtY2EtMUB3
    LmxhbjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKcZtT1P/iHd5mLA
    Tj+p1Sv3qCzG7w8B9MNsvZAKRR/how+4WspBlE5scVrbBwgn82fdF1U35qzsts/g
    vNfcL9ziSb91z1XLfzPOqdOoI7Q9DD4pyPv5bJFjhz0fm4iPlqu1aBfYRHOcEdWB
    thl7hobh3BCa6rO8MzCuQZ0NEva7uNYztHw3T+X3/yuSOnW6gViibANZliK1bRFk
    lk/w52ol/Vs7eNsUzv6wXcWB05hCt4IkvENTh0H/Pa/imegEK7wufKRHTQwwBzlR
    GlNuttRHeJbCdE+L0Gzp2MMDE/YxbgUPbAbUg9o1Dnm4yu98haDOXKU9d2RelvU6
    1Gg7QACiSfqoOY40Ad2ifYNH2iumDj4PTRYE99wW3klqdXpHL6JkR9nIu0dCjAlh
    pKRyjhmQ/rOF6n0tL2iCorIQNK7rqakNmmdrjRkpCLOcBkx171iIC0+UjxyL3jCD
    j3Rq6yPxEzGN5IrbdgyZUQ9NoPsEkEhVlZn8KBvdD121/RZSFO+0ZFDC2mNfYFbG
    /GZtPe1ZuCZS4Ka4A8b66SA0AGjAR/QNq+hjzH0x9bW8IO4whmaij7bJGgjnqHC4
    oFNT2snnecTK3UTWjwLS/W+/KhhEYlP5zS6RbXBzB8xY7BaiR3wmUFO8QUWM/Qh4
    61tokMOfuhyO1Ay/wKoGT0CgJ4nNAgMBAAGjgYcwgYQwDwYDVR0TAQH/BAUwAwEB
    /zAOBgNVHQ8BAf8EBAMCAcYwIQYDVR0RBBowGIEWd2Nvb2tlLXJvb3QtY2EtMUB3
    LmxhbjAdBgNVHQ4EFgQUlSA6SHY9qUxMnUKhf6+zu0W+KXQwHwYDVR0jBBgwFoAU
    lSA6SHY9qUxMnUKhf6+zu0W+KXQwDQYJKoZIhvcNAQELBQADggIBADNdWfV9KS5l
    NEadQjhMH0vXg5lPVtwhVdPLAC03FuDZ2qyn4i++0Q6XsfTNC0o2u/wwijJj5s2p
    qxlK22fx0Z6FwcWD4i36XwYGTkz+nZkIz5Cu6cJo905i/CjeRi1zvHYoGQTclSQy
    ZvhZo+lv77ruEmb5PhzLblvnzkRZ2CXTIt3xXYCo3L5Tspd81eT4rvdpcJ387Vwc
    I3jfuJRMCGB6fwBLOXRssjbItYOj0EvR+a81D5V5IfcONb3Ws+bPh4+SooQPqSCH
    o19GXRezsV3pvKsWNiVphwMj/U6RYxEL0lQUINE0RgDZeL6U3d4AiyfLOsccHDW1
    ceJZo8R3Rvg2AIpE3agpimTCTFZ6FTFHMJyTUVXP+a/UG5+VQ6yQpSFlFhufp3US
    6P4Fc0X8X4h6PwOq0ePc9TSGBGqBv0n6BPWzWI88Gchm9TnMdylbFJKXBuxLIVw+
    hgApN6JUGdVpyCyH0mNCAAVDweett2k0Jtl3s39qRFJiExPfeHBizYBVH3ojL1Zo
    c0alEC/DrTg7NJ35ZmMtdVkJM2QRMPar68eFveBuAjIlNVfL/X3rWn9ysMKTMq5r
    Pz1DZp0qxAc7eGd+SgTQJt2LTVjB6wGG7pWebI5vNlkbiOfROpqCfcUQR727FZjE
    EYORZixooIg8wvIOHlE6xVB7t2TUOraL
    -----END CERTIFICATE-----
