apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: gitlab-registry-bucket
spec:
  bucketName: gitlab-registry
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "1000000"
    maxSize: "50G"
    bucketPolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam:::user/gitlab-ceph-user"
              ]
            },
            "Action": "s3:*",
            "Resource": "*"
          }
        ]
      }
