apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
      - livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 6060
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 7
          successThreshold: 1
          timeoutSeconds: 1
        name: trust-manager
