---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-core-config
  namespace: harbor
spec:
  encryptedData:
    CONFIG_OVERWRITE_JSON: AgAEMfCSCXcjug+3q+vAxigqCii6RwnPZ2ZVmq6WjhILRuzup1kcjIiePXGOLpgqqdjBv9PG8bnXvcyM6mba8QFd8t+/tnXB93ckCDDDdSyt65/sCb9jvAud8sAjLK52PdxNbL0wNkLHlpEQxTEnIPXu6ywIcXouXd796vNO5NsJdCrR4dVWm/3+3MucWk3eGbPRo6xniN0EYuVCzhoI1JuxXE7cRcF84ByyZJgnMdM6OEhtnQOjyBVu9CnuCP07agHmsBXT0rzxFy8L+PQBXrvwxsJqRJdM+mHKHNgJjQlslXnKkKPYeMi0G6l6Id1JEwHyt94CaQMSzOoGJD+9l0/wAK91A2Kp4sT1e4FNrQcngtjc3q83rO4e8IOx5/SlRKgCh9ej+XYCiuvn9Hwlh0C32jGpK3rSWxR5cP120dXPn6IjumQ1sqFbCwB0BaVSaeqAsWIkXdSnH/n+Z+z5kmx9NtHbGJz3EwGryqUj6Z2NbotuxvQXMTpeE/u/HwWefN1Ycu7+zqBcpxxOqjj0a5ihAXsc2zP7tonWeH/zFnp7yZh8ua7Kih5rcTu8I/CAlYdV4bRfKRdJXK+WERw0JjEbpMqFZQriDMzQ2WTMOW7xlOH/BebqJgqu5VyZxhmrMoggay5MpSHLsAEUpYRdsbnzggpsClM+HvsDjOqY0uvT2xDfR5TZF1HaPOu7GjKpXCSYAyEKEWDyKESFP8wM4PPteSbnhUPP9l3ZP3iuyOYutj7xq6BMlzgbjSEEgi2wNELnX8dBxJdjebzkk4Wa6JeHqGDsSahjSoWV9cV9PA1P1xbFDXpChEuWHednLH3vY5YJF2LepJYV5zum5qXKFfmKCC4ckYrRnMMxz0ydXTbBhEeuUdwcb1ItnCdmZjU7aSaNyQ8OyYIOdXDBvVwukvZzH+FoNkBpC35zBJ1QULCmNj12aHkW+cTtrIC5Ajo02aj3nt2r+bBMlTaoCSBa58Pr/pSIRHUAJGpo2bUzV5aP59mmgvwD/hcD1hB4I7Jnq9GYlJa9E44WPHaV3SZ9MS08FXmoYVybW+2S8WrGxRh0fSniL+WBmzZ6UQFl4a6jg8ZVCQxovEwXj78jTscIaFu1FXNR64o3nnOn7VjKUZr5WFu6TMhhRMxpUQcJyeaNVWPZEc5JI8o4WH1Oel4DTpS3UmyiD8NDmHYEsUIkeYnHVZ1znrxTEDHlBjnAcg3MSOFyyel9mVSveMsLeqz4CqKQcOYUHbfRRlq3vuixckDX7I/Kyitf9L0aTmZ4doxEF9xmri0SC9XQJZwFEtBGTno59MclyeP48tWbcX6tYtPe1uppC7e1FQg4nwFo6daHylXm8/lsx5xU5uCfSC6gcmGK45qMvqwEzPjmHoomsnL99+g/ZSJYqqN0y2nnz0fo9M0dE5bxzfUo1sX3M0RyAtU786e70mnGrj0JfuioPFh3SeqCrh/ND/6ULWc61A166nNUD+n0mXvnHQSjObjWTft1ZqycXV00+Gc3I/Yg3s2h6qYSuaFAC8I0e7f26HmZHEGAcmvEol04k7qolBbM7ls4GkJbHrgdVUrXe3Uheu/1v24Id/Gy1E/DHVEdgqfXciKV4I2rpie44TNC0w==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-core-config
      namespace: harbor
    type: stringData
