---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCdAopH+oXqYOyzaY5TO3rpz0qimsyqJANRugq3J/E+29/GDkBaQ4Xr1KHEwnZsgWIeieGaHIE0vO0mbBsujyMOUuOML58sc9Q3RUls7PfgLBaKOHULC6eZMXqPfaPSrDTcVRMHeiBEIUU82tmCiXdDPGf/RS5fh4PFtx0cVMhbWzFaBZef/qZzKzoKb89SagJICQwcXFbLC5zqERP3uqhiN7okkuXkbKOMpnpDDE/eK66BYxvyCp1zVBPBID1/Myrv0nJkBkjmJCygA0TTU+LJwEMrnUL0c3AK0w+hU2tCXJocndTqGxMNTNHZTsTkm7WbpKT/S2ffp7D60mq1RvzVmeMDeVV1yyyR3Yapl2TEJs8y7RIgyYmTFItZn/bArkBcTQdnCiVDjPeniIwnP1OKdp8Tokmm5DlbFZqMw8ktenXCR8aWnzDq0+ULUzO4gg9T8bs0XpAih95Yng6CDExV0YlP6T9OmJKAqcyw1W1OmPF6xNiOmFgx0Aus7qa9x9rR1o8HGonDa9aSFCInQc9fxhn8QWMuCaAsr3iV+og1BY19APUwnjzjyjZNcgZWHzy0aFs9fL2rMNuE0vEB8+haIzuyNQB3QogXWRWnIrHv+QZadP/4IRkJhUfmQ/LTsHFR+tBGQun7dzBsy5O26nbgJx16XrUf43ZD2uNmOl/u9d8BDcSN4Ei/qjgS/133fc8NiB/3fAo=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-password
      namespace: harbor
    type: stringData
