apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
- name: trust-manager
  namespace: cert-manager
  releaseName: trust-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yml
  version: v0.19.0

patches:
- path: patches/liveness-probe.yml
