app:
  logFormat: json

  metrics:
    service:
      servicemonitor:
        enabled: true

filterExpiredCertificates:
  enabled: true

replicaCount: 2

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi

secretTargets:
  enabled: true
  authorizedSecrets:
  - ca-bundle-secret
