# https://developers.redhat.com/articles/2025/02/17/how-securely-deploy-github-arc-openshift#how_to_run_arc_images_on_openshift
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:github-arc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - github-arc
  resources:
  - securitycontextconstraints
  verbs:
  - use
