apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: okd
spec:
  addresses:
  - 10.42.41.100-10.42.41.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: okd
  namespace: metallb-system
spec:
  ipAddressPools:
  - okd
