apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 100-master-iommu
spec:
  config:
    ignition:
      version: 3.5.0
  kernelArguments:
  - intel_iommu=on
  - iommu=pt
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 100-worker-iommu
spec:
  config:
    ignition:
      version: 3.5.0
  kernelArguments:
  - intel_iommu=on
  - iommu=pt
