---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pull-secret
  namespace: openshift-config
spec:
  encryptedData:
    .dockerconfigjson: AgCO+NW2k+KXrLcBaZ7afeqWCkCdFugQsLycE4pT3cXCXDpCGOa25ddi6ScFxWpCPgpkx/itPuzeMgyWB4hKNTFCDuGI8j1cBWpHH037s9LiTEIx7we/vTICOWDP4lZII28MOb7uGA15W9mJAEYiCkv/IR30O66TtfmIRdHzQTUc+0qRmYCU6/nu0AhddORTkEV1X4PRvtksk2lrAqQK2f0dlwUHylKNboDZAuIeDqFFwnxLqqskf4WTEQluEAXIIb5m1adV4+D+FHGtz/JqegJjDSgBdXRD9F13gzckZNhdYXRCztPRJhkiWklwAt2gSvjIa4tPMUDxRe2IB3ZQRMA981zss5rd+rmegS+3gCtx4AOuagSOj8Hkygqw8V5Lhh4UsmPAeH05yYpVDTwNOPbBMbrFN/n13nWCovrNV7zIwUBzVn2uZazL35aFnLJ5PoEv9RpiY48ToW0hocYoFHT+Ew+oVU2s/feILuSZQd1+Ey3YKSj/fAMh8q9RaC1/2HajxRHBz9eBnTN2wYEkA6us2uWjIWdts+npwqXi0D63cHPSmuJenGeee98Cc76p1i3bEaQbrMo8vUd7Y2Y0zjBWHkWgeQC6YbGLIlp8xDQ00eQq/QlI+fXfH9w/x0Nw3YzHyRvWkx3EnaZFhNw8rKSaaIjw37S3Sb13oFmr3seL882Kk4suVLiOPXim9waJ6gw/+Kq7uls04Q43/nYuipcN0kLGW3VPmMfwEOUDSaM0oDsJvS2dCKP2k9CZiXPESkScLo3KuMBoE23UT8dr/I1wy6NHIIpJFVOBtMtijcZkOw1c08QZVLZ4+0LcBQvsd5omVQ/i6xoboMHqK20w90akzx2xmhu5UGfMCbkEf2lEJ4nhDjrpO99mXiYBT5UagOto7SZmKQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: pull-secret
      namespace: openshift-config
    type: kubernetes.io/dockerconfigjson
