apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-session-start-end-time-master
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
      - contents:
          source: data:,-w%20/var/log/btmp%20-p%20wa%20-k%20session%0A
        mode: 0644
        path: /etc/audit/rules.d/75-var_log_btmp_write_events.rules
        overwrite: true
      - contents:
          source: data:,-w%20/var/log/utmp%20-p%20wa%20-k%20session%0A
        mode: 0644
        path: /etc/audit/rules.d/75-var_log_utmp_write_events.rules
        overwrite: true
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-session-start-end-time-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
      - contents:
          source: data:,-w%20/var/log/btmp%20-p%20wa%20-k%20session%0A
        mode: 0644
        path: /etc/audit/rules.d/75-var_log_btmp_write_events.rules
        overwrite: true
      - contents:
          source: data:,-w%20/var/log/utmp%20-p%20wa%20-k%20session%0A
        mode: 0644
        path: /etc/audit/rules.d/75-var_log_utmp_write_events.rules
        overwrite: true
