apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-concurrent-logons-rules-master
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
      - contents:
          source: data:,-w%20/var/run/faillock%20-p%20wa%20-k%20logins%0A
        mode: 0644
        path: /etc/audit/rules.d/75-faillock_login_events.rules
        overwrite: true
      - contents:
          source: data:,-w%20/var/log/lastlog%20-p%20wa%20-k%20logins%0A
        mode: 0644
        path: /etc/audit/rules.d/75-lastlog_login_events.rules
        overwrite: true
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 75-concurrent-logons-rules-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
      - contents:
          source: data:,-w%20/var/run/faillock%20-p%20wa%20-k%20logins%0A
        mode: 0644
        path: /etc/audit/rules.d/75-faillock_login_events.rules
        overwrite: true
      - contents:
          source: data:,-w%20/var/log/lastlog%20-p%20wa%20-k%20logins%0A
        mode: 0644
        path: /etc/audit/rules.d/75-lastlog_login_events.rules
        overwrite: true
