apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 90-chrony-ntp-servers-set-master
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.5.0
      storage:
        files:
        - contents:
            source: data:,%23%20Use%20public%20servers%20from%20the%20pool%2Entp%2Eorg%20project%2E%0D%0A%23%20Please%20consider%20joining%20the%20pool%20%28https%3A%2F%2Fwww%2Epool%2Entp%2Eorg%2Fjoin%2Ehtml%29%2E%0D%0A%23pool%202%2Ecentos%2Epool%2Entp%2Eorg%20iburst%0D%0Ainclude%20%2Fetc%2Fchrony%2Ed%2F%2A%2Econf%0D%0A%0D%0A%23%20Use%20NTP%20servers%20from%20DHCP%2E%0D%0A%23sourcedir%20%2Frun%2Fchrony%2Ddhcp%0D%0A%0D%0A%23%20Record%20the%20rate%20at%20which%20the%20system%20clock%20gains%2Flosses%20time%2E%0D%0Adriftfile%20%2Fvar%2Flib%2Fchrony%2Fdrift%0D%0A%0D%0A%23%20Allow%20the%20system%20clock%20to%20be%20stepped%20in%20the%20first%20three%20updates%0D%0A%23%20if%20its%20offset%20is%20larger%20than%201%20second%2E%0D%0Amakestep%201%2E0%203%0D%0A%0D%0A%23%20Enable%20kernel%20synchronization%20of%20the%20real%2Dtime%20clock%20%28RTC%29%2E%0D%0Artcsync%0D%0A%0D%0A%23%20Enable%20hardware%20timestamping%20on%20all%20interfaces%20that%20support%20it%2E%0D%0A%23hwtimestamp%20%2A%0D%0A%0D%0A%23%20Increase%20the%20minimum%20number%20of%20selectable%20sources%20required%20to%20adjust%0D%0A%23%20the%20system%20clock%2E%0D%0A%23minsources%202%0D%0A%0D%0A%23%20Allow%20NTP%20client%20access%20from%20local%20network%2E%0D%0A%23allow%20192%2E168%2E0%2E0%2F16%0D%0A%0D%0A%23%20Serve%20time%20even%20if%20not%20synchronized%20to%20a%20time%20source%2E%0D%0A%23local%20stratum%2010%0D%0A%0D%0A%23%20Require%20authentication%20%28nts%20or%20key%20option%29%20for%20all%20NTP%20sources%2E%0D%0A%23authselectmode%20require%0D%0A%0D%0A%23%20Specify%20file%20containing%20keys%20for%20NTP%20authentication%2E%0D%0Akeyfile%20%2Fetc%2Fchrony%2Ekeys%0D%0A%0D%0A%23%20Save%20NTS%20keys%20and%20cookies%2E%0D%0Antsdumpdir%20%2Fvar%2Flib%2Fchrony%0D%0A%0D%0A%23%20Insert%2Fdelete%20leap%20seconds%20by%20slewing%20instead%20of%20stepping%2E%0D%0A%23leapsecmode%20slew%0D%0A%0D%0A%23%20Get%20TAI%2DUTC%20offset%20and%20leap%20seconds%20from%20the%20system%20tz%20database%2E%0D%0Aleapsectz%20right%2FUTC%0D%0A%0D%0A%23%20Specify%20directory%20for%20log%20files%2E%0D%0Alogdir%20%2Fvar%2Flog%2Fchrony%0D%0A%0D%0A%23%20Select%20which%20information%20is%20logged%2E%0D%0A%23log%20measurements%20statistics%20tracking
            mode: 420
            overwrite: true
            path: /etc/chrony.conf
        - contents:
            source: data:,
          mode: 420
          overwrite: true
          path: /etc/chrony.d/.mco-keep
        - contents:
             source: data:,server%2010.42.16.21%20minpoll%204%20maxpoll%2010%0Aserver%2010.42.16.22%20minpoll%204%20maxpoll%2010
          mode: 420
          overwrite: true
          path: /etc/chrony.d/ntp-server.conf
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 90-chrony-ntp-servers-set-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.5.0
      storage:
        files:
        - contents:
            source: data:,%23%20Use%20public%20servers%20from%20the%20pool%2Entp%2Eorg%20project%2E%0D%0A%23%20Please%20consider%20joining%20the%20pool%20%28https%3A%2F%2Fwww%2Epool%2Entp%2Eorg%2Fjoin%2Ehtml%29%2E%0D%0A%23pool%202%2Ecentos%2Epool%2Entp%2Eorg%20iburst%0D%0Ainclude%20%2Fetc%2Fchrony%2Ed%2F%2A%2Econf%0D%0A%0D%0A%23%20Use%20NTP%20servers%20from%20DHCP%2E%0D%0A%23sourcedir%20%2Frun%2Fchrony%2Ddhcp%0D%0A%0D%0A%23%20Record%20the%20rate%20at%20which%20the%20system%20clock%20gains%2Flosses%20time%2E%0D%0Adriftfile%20%2Fvar%2Flib%2Fchrony%2Fdrift%0D%0A%0D%0A%23%20Allow%20the%20system%20clock%20to%20be%20stepped%20in%20the%20first%20three%20updates%0D%0A%23%20if%20its%20offset%20is%20larger%20than%201%20second%2E%0D%0Amakestep%201%2E0%203%0D%0A%0D%0A%23%20Enable%20kernel%20synchronization%20of%20the%20real%2Dtime%20clock%20%28RTC%29%2E%0D%0Artcsync%0D%0A%0D%0A%23%20Enable%20hardware%20timestamping%20on%20all%20interfaces%20that%20support%20it%2E%0D%0A%23hwtimestamp%20%2A%0D%0A%0D%0A%23%20Increase%20the%20minimum%20number%20of%20selectable%20sources%20required%20to%20adjust%0D%0A%23%20the%20system%20clock%2E%0D%0A%23minsources%202%0D%0A%0D%0A%23%20Allow%20NTP%20client%20access%20from%20local%20network%2E%0D%0A%23allow%20192%2E168%2E0%2E0%2F16%0D%0A%0D%0A%23%20Serve%20time%20even%20if%20not%20synchronized%20to%20a%20time%20source%2E%0D%0A%23local%20stratum%2010%0D%0A%0D%0A%23%20Require%20authentication%20%28nts%20or%20key%20option%29%20for%20all%20NTP%20sources%2E%0D%0A%23authselectmode%20require%0D%0A%0D%0A%23%20Specify%20file%20containing%20keys%20for%20NTP%20authentication%2E%0D%0Akeyfile%20%2Fetc%2Fchrony%2Ekeys%0D%0A%0D%0A%23%20Save%20NTS%20keys%20and%20cookies%2E%0D%0Antsdumpdir%20%2Fvar%2Flib%2Fchrony%0D%0A%0D%0A%23%20Insert%2Fdelete%20leap%20seconds%20by%20slewing%20instead%20of%20stepping%2E%0D%0A%23leapsecmode%20slew%0D%0A%0D%0A%23%20Get%20TAI%2DUTC%20offset%20and%20leap%20seconds%20from%20the%20system%20tz%20database%2E%0D%0Aleapsectz%20right%2FUTC%0D%0A%0D%0A%23%20Specify%20directory%20for%20log%20files%2E%0D%0Alogdir%20%2Fvar%2Flog%2Fchrony%0D%0A%0D%0A%23%20Select%20which%20information%20is%20logged%2E%0D%0A%23log%20measurements%20statistics%20tracking
            mode: 420
            overwrite: true
            path: /etc/chrony.conf
        - contents:
            source: data:,
          mode: 420
          overwrite: true
          path: /etc/chrony.d/.mco-keep
        - contents:
             source: data:,server%2010.42.16.21%20minpoll%204%20maxpoll%2010%0Aserver%2010.42.16.22%20minpoll%204%20maxpoll%2010
          mode: 420
          overwrite: true
          path: /etc/chrony.d/ntp-server.conf
