apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rocky-linux9-server-small
  annotations:
    openshift.io/display-name: Rocky Linux 9 VM
    description: >-
      Template for Rocky Linux 9 VM or newer.
      A PVC with the Rocky Linux disk image must be available.
    tags: "hidden,kubevirt,virtualmachine,linux,rockylinux"
    iconClass: icon-rockylinux
    openshift.io/provider-display-name: Custom
    template.openshift.io/bindable: "false"
    template.kubevirt.io/version: v1alpha1
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/images: |
      https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-LVM.latest.x86_64.qcow2
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.memory.guest
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    name.os.template.kubevirt.io/rocky-linux: Rocky Linux 9 or higher
  labels:
    flavor.template.kubevirt.io/small: "true"
    os.template.kubevirt.io/rocky-linux: "true"
    template.kubevirt.io/type: vm
    template.kubevirt.io/version: "v0.34.1"
    template.kubevirt.io/architecture: "amd64"
    workload.template.kubevirt.io/server: "true"
objects:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    name: ${NAME}
    labels:
      vm.kubevirt.io/template: rocky-linux-server-small
      vm.kubevirt.io/template.version: "v0.34.1"
      vm.kubevirt.io/template.revision: "1"
      app: ${NAME}
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.memory.guest",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: ${NAME}
      spec:
        storage:
          resources:
            requests:
              storage: 30Gi
        sourceRef:
          kind: DataSource
          name: ${DATA_SOURCE_NAME}
          namespace: ${DATA_SOURCE_NAMESPACE}
    runStrategy: Halted
    template:
      metadata:
        annotations:
          vm.kubevirt.io/os: "rocky-linux9"
          vm.kubevirt.io/workload: "server"
          vm.kubevirt.io/flavor: "small"
        labels:
          kubevirt.io/domain: ${NAME}
          kubevirt.io/size: small
      spec:
        architecture: amd64
        domain:
          cpu:
            sockets: 1
            cores: 1
            threads: 1
          memory:
            guest: 2Gi
          devices:
            rng: {}
            disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
              model: virtio
        terminationGracePeriodSeconds: 30
        networks:
        - name: default
          pod: {}
        volumes:
        - dataVolume:
            name: ${NAME}
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: rocky
              password: ${CLOUD_USER_PASSWORD}
              chpasswd: { expire: False }
          name: cloudinitdisk
parameters:
- description: VM name
  from: 'rocky-linux9-[a-z0-9]{16}'
  generate: expression
  name: NAME
- name: DATA_SOURCE_NAME
  description: Name of the DataSource to clone
  value: 'rocky-linux9'
- name: DATA_SOURCE_NAMESPACE
  description: Namespace of the DataSource
  value: kubevirt-templates
- description: Randomized password for the cloud-init user rocky
  from: '[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}'
  generate: expression
  name: CLOUD_USER_PASSWORD
