admin:
  existingSecret: grafana-admin

extraConfigmapMounts:
- name: ca-bundle
  mountPath: /ca-bundle
  configMap: ca-bundle
  readOnly: true
  optional: false

extraSecretMounts:
- name: grafana-pg-cluster-app
  mountPath: /grafana-pg-cluster-app
  secretName: grafana-pg-cluster-app
  readOnly: true
  optional: false
- name: grafana-keycloak-client
  mountPath: /grafana-keycloak-client
  secretName: grafana-keycloak-client
  readOnly: true
  optional: false

grafana.ini:
  analytics:
    enabled: false
    feedback_links_enabled: false
    check_for_plugin_updates: false
    check_for_updates: false
    reporting_enabled: false
  database:
    type: postgres
    host: "$__file{/grafana-pg-cluster-app/host}:$__file{/grafana-pg-cluster-app/port}"
    name: "$__file{/grafana-pg-cluster-app/dbname}"
    user: "$__file{/grafana-pg-cluster-app/user}"
    password: "$__file{/grafana-pg-cluster-app/password}"
  grafana_net:
    url: https://grafana.net
  news:
    news_feed_enabled: false
  security:
    allow_embedding: true
  server:
    root_url: https://grafana.apps.iaas.wcooke.me
  feature_toggles:
    provisioning: true
    kubernetesClientDashboardsFolders: true
    kubernetesDashboards: true # use k8s from browser
    # If you want easy kubectl setup development mode
    grafanaAPIServerEnsureKubectlAccess: true
  auth.generic_oauth:
    enabled: true
    name: Keycloak
    allow_sign_up: true
    client_id: "$__file{/grafana-keycloak-client/client-id}"
    client_secret: "$__file{/grafana-keycloak-client/client-secret}"
    scopes: openid email profile offline_access roles
    email_attribute_path: email
    login_attribute_path: sub
    name_attribute_path: name
    auth_url: https://keycloak.apps.iaas.wcooke.me/realms/IaaS/protocol/openid-connect/auth
    token_url: https://keycloak.apps.iaas.wcooke.me/realms/IaaS/protocol/openid-connect/token
    api_url: https://keycloak.apps.iaas.wcooke.me/realms/IaaS/protocol/openid-connect/userinfo
    # groups_attribute_path: groups
    signout_redirect_url: https://keycloak.apps.iaas.wcooke.me/realms/IaaS/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fgrafana.apps.iaas.wcooke.me%2Flogin
    # role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
    role_attribute_path: contains(realm_access.roles[*], 'grafana-server-admin') && 'GrafanaAdmin' || contains(realm_access.roles[*], 'grafana-admin') && 'Admin' || contains(realm_access.roles[*], 'grafana-editor') && 'Editor' || 'Viewer'
    allow_assign_grafana_admin: true
    use_refresh_token: true
    auto_login: true
    tls_client_ca: /ca-bundle/cabundle
  auth.security:
    protected_roles: server_admins

ingress:
  annotations:
    cert-manager.io/cluster-issuer: iaas-wcooke-me
    forecastle.stakater.com/appName: Grafana
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: Observability
    forecastle.stakater.com/icon: https://grafana.apps.iaas.wcooke.me/public/img/grafana_icon.svg
    forecastle.stakater.com/network-restricted: "true"
  enabled: true
  hosts:
  - grafana.apps.iaas.wcooke.me
  ingressClassName: openshift-default
  tls:
  - hosts:
    - grafana.apps.iaas.wcooke.me
    secretName: grafana-ingress-tls

initChownData:
  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 50m
      memory: 16Mi

replicas: 2

resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

serviceMonitorSelector:
  enabled: true

sidecar:
  alerts:
    enabled: true
    searchNamespace: ALL
  dashboards:
    enabled: true
    searchNamespace: ALL
  datasources:
    enabled: true
    searchNamespace: ALL
  plugins:
    enabled: true
    searchNamespace: ALL
  notifiers:
    enabled: true
    searchNamespace: ALL
